
spring.application.name=pixben

spring.datasource.url=jdbc:postgresql://ep-steep-silence-atbxobnd.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_5bmcZsnNFt8C

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.data.mongodb.uri=mongodb+srv://sebastian12hh_db_user:vfnF8O6fAHytjjuE@cluster0.ve2pfj5.mongodb.net/pixben?retryWrites=true&w=majority&appName=Cluster0